image: mono:latest

stages:
    - build
    - test

variables:
    solution: "AltaPayApi.sln"
    test: "AltaPayApi.Tests"

before_script:
    - cd AltaPayApi/
    - nuget restore -NonInteractive

build:
    stage: build
    script:
        echo "building"
        #- msbuild /p:Configuration=Debug $solution

test:
    stage: test
    script:
        echo "testing"
        #- msbuild /p:Configuration=Debug $solution
        #- mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./$test/bin/Release/$test.dll