name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '4.6.1', '5.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - uses: actions/checkout@v2 
    - name: Restore dependencies
      run: dotnet restore  AltaPayApi/AltaPayApi.Tests/AltaPayApi.Tests.csproj
    - name: Build
      run: dotnet build AltaPayApi/AltaPayApi.Tests/AltaPayApi.Tests.csproj --no-restore
    - name: Test
      run: dotnet test AltaPayApi/AltaPayApi.Tests/AltaPayApi.Tests.csproj --no-build --verbosity normal

